//! Memory DTOs with the Fact ≠ Inference contract (PRD §17/§19, P0 requirement).

use sdkwork_utils_rust::serde_uint64;
use serde::{Deserialize, Serialize};

use super::Importance;

/// Memory category (PRD §17).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryType {
    /// Long-term fact ("李明是一名产品经理").
    Semantic,
    /// Concrete experience ("2026 年 5 月和李明一起去杭州").
    Episodic,
    /// Time-varying information ("以前在 A 公司，现在已经离职").
    Temporal,
    /// Relationship fact ("李明是我的大学同学").
    Relationship,
    /// Preference ("李明喜欢摄影").
    Preference,
    /// Commitment or promise ("我答应帮李明介绍一个客户").
    Commitment,
}

/// Memory lifecycle status (PRD §35).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryStatus {
    /// Extracted or drafted, awaiting user confirmation.
    Candidate,
    /// User-confirmed fact.
    Confirmed,
    /// Rejected by the user.
    Rejected,
    /// Archived (kept, out of active recall).
    Archived,
    /// Expired by retention rules.
    Expired,
}

/// Origin separation: explicit facts vs AI inference (PRD §19, P0).
///
/// `inference` records must carry [`Memory::confidence`] and
/// [`Memory::source_reason`]; an inference is never auto-promoted to a fact —
/// only the user confirm command can move it to [`MemoryStatus::Confirmed`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryOrigin {
    /// Explicit fact with a clear source.
    Fact,
    /// AI inference requiring user confirmation.
    Inference,
}

/// Where a memory came from (PRD §32.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SourceKind {
    /// Typed by the user.
    UserInput,
    /// Extracted from an uploaded file.
    File,
    /// Extracted from pasted or imported conversation text.
    Conversation,
    /// Extracted by AI from user-provided text.
    AiExtraction,
    /// Inferred by AI.
    AiInference,
    /// Generated by the system.
    System,
}

impl SourceKind {
    /// Normalized source with `user_input` as the manual default.
    pub fn or_user_input(value: Option<Self>) -> Self {
        value.unwrap_or(Self::UserInput)
    }
}

/// A structured memory record (PRD §35 schema).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Memory {
    /// Snowflake memory id (wire: string).
    #[serde(
        serialize_with = "serde_uint64::serialize",
        deserialize_with = "serde_uint64::deserialize"
    )]
    pub id: u64,
    /// Owning person id (wire: string).
    #[serde(
        serialize_with = "serde_uint64::serialize",
        deserialize_with = "serde_uint64::deserialize"
    )]
    pub person_id: u64,
    /// Linking story id, when the memory belongs to a story (wire: string).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        serialize_with = "serde_uint64::option::serialize",
        deserialize_with = "serde_uint64::option::deserialize"
    )]
    pub story_id: Option<u64>,
    /// Memory category.
    #[serde(rename = "type")]
    pub memory_type: MemoryType,
    /// Short title.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Memory content text.
    pub content: String,
    /// Fact vs inference origin (`origin` on the wire keeps the PRD name).
    pub origin: MemoryOrigin,
    /// Lifecycle status.
    pub status: MemoryStatus,
    /// Inference-only confidence in `[0,1]`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    /// Inference-only reasoning note.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_reason: Option<String>,
    /// Where the memory came from.
    pub source_kind: SourceKind,
    /// Free-form source reference (file id, chat id, ...).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_ref: Option<String>,
    /// Importance.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub importance: Option<Importance>,
    /// When the remembered event happened (RFC 3339), if known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<String>,
    /// Creation timestamp (RFC 3339).
    pub created_at: String,
    /// Last update timestamp (RFC 3339).
    pub updated_at: String,
}

/// Create/update request for a manual memory record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryUpsertRequest {
    /// Owning person id (wire: string).
    #[serde(
        serialize_with = "serde_uint64::serialize",
        deserialize_with = "serde_uint64::deserialize"
    )]
    pub person_id: u64,
    /// Linking story id (wire: string).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        serialize_with = "serde_uint64::option::serialize",
        deserialize_with = "serde_uint64::option::deserialize"
    )]
    pub story_id: Option<u64>,
    /// Memory category.
    #[serde(rename = "type")]
    pub memory_type: MemoryType,
    /// Short title.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Memory content text (1..=4000 chars).
    pub content: String,
    /// Importance.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub importance: Option<Importance>,
    /// When the remembered event happened (RFC 3339).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<String>,
    /// Source kind; defaults to `user-input` for manual records.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_kind: Option<SourceKind>,
    /// Free-form source reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_ref: Option<String>,
}

/// Free-text memory extraction request (AI assist; produces candidates only).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryExtractRequest {
    /// Target person id; when omitted, resolved by name mentions in the text.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        serialize_with = "serde_uint64::option::serialize",
        deserialize_with = "serde_uint64::option::deserialize"
    )]
    pub person_id: Option<u64>,
    /// Free text to extract from (1..=20000 chars).
    pub text: String,
}
